### ISSUE TITLE
Compilation failures on CentOS 7 / Oracle Linux 7

### ISSUE THREAD

**Issue by victor-dumitrescu** [hacl-star/hacl-star#484]
This issue has been raised before in the now archived [mirage/hacl](https://github.com/mirage/hacl/issues/46) package. Both distributions use gcc 4.8.5 and this seems to be the source of these issues:

1. lack of support for the `__has_include` operator, which is used in several files in the C snapshot:
```
gcc-compatible/Lib_Memzero0.c:#if __has_include("config.h")
gcc-compatible/evercrypt_targetconfig.h:#if __has_include("config.h")
gcc-compatible/libintvector.h:#if __has_include("config.h")
gcc-compatible/libintvector.h:#if __has_include("libintvector_debug.h")
gcc-compatible/lib_intrinsics.h:#if __has_include("config.h")
```

2. errors compiling intrinsics:
```
- In file included from libintvector.h:25:0,
-                  from Lib_RandomBuffer_System.h:33,
-                  from Lib_RandomBuffer_System.c:1:
- /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/tmmintrin.h:31:3: error: #error "SSSE3 instruction set not enabled"
-  # error "SSSE3 instruction set not enabled"
-    ^
- In file included from libintvector.h:26:0,
-                  from Lib_RandomBuffer_System.h:33,
-                  from Lib_RandomBuffer_System.c:1:
- /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/smmintrin.h:31:3: error: #error "SSE4.1 instruction set not enabled"
-  # error "SSE4.1 instruction set not enabled"
-    ^
- In file included from libintvector.h:227:0,
-                  from Lib_RandomBuffer_System.h:33,
-                  from Lib_RandomBuffer_System.c:1:
- /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/wmmintrin.h:34:3: error: #error "AES/PCLMUL instructions not enabled"
-  # error "AES/PCLMUL instructions not enabled"
```

**Comment by msprotz** [comment]
Regarding __has_include: to be removed in https://github.com/hacl-star/hacl-star/pull/561

Regarding compiler warnings for SSE3: is this something that is now handled properly in hacl-packages? @franziskuskiefer

**Comment by franziskuskiefer** [comment]
The error doesn't show up in hacl-packages but we don't compile with 4.8.5.
Can we even compile the code with gcc 4.8.5?

**Comment by msprotz** [comment]
@victor-dumitrescu is this still a use-case? this compiler is > 7 years old now

**Comment by victor-dumitrescu** [comment]
I don't think this is relevant any more. opam CI also [stopped testing for it](https://github.com/ocaml/opam-repository/pull/22596#discussion_r1037429671) in the meantime, so we can also remove the `x-ci-accept-failures: ["centos-7" "oraclelinux-7"]` from the opam file
